
server:
  port: 9003

spring:
  application:
    name: mall-gateway

#\u8868\u793A\u901A\u8FC7\u6CE8\u518C\u4E2D\u5FC3\u7684\u670D\u52A1\u540D\u8FDB\u884C\u8F6C\u53D1\u751F\u6548
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
      routes:
        - id: login
          uri: lb://mall-login
          predicates:
            - Path=/**
          filters:
              # {} \u662F\u7528\u6765\u53D6\u503C\u7684
            #- RewritePath=/api/(?<segment>.*), /$\{segment}
eureka:
  client:
    service-url:
      defaultZone: http://localhost:9002/eureka/


